name: waybill_sender
description: A Flutter app for Waybill Sender.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.2"

dependencies:
  flutter_launcher_icons: ^0.9.0

  flutter:
    sdk: flutter
analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true

flutter_icons:
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF"
  image_path: "assets/images/logo_launcher.png"
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icon/icon.png"
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  #Flutter Dependencies here
  #media
  flutter_svg: ^0.22.0
  grouped_buttons: ^1.0.4
  lottie: ^1.0.1
  #tests
  #security
  local_auth: ^1.1.7
  flutter_dotenv: ^5.0.2
  #network requests
  http: ^0.13.3
  dio: ^4.0.0
  #locator
  email_validator: ^2.0.1
  # animations
  #persistence
  shared_preferences: ^2.0.6
  #database

  #widgets
  modal_bottom_sheet: ^2.0.0
  fluttertoast: ^8.0.7
  google_maps_flutter: ^2.0.3
  bubble: ^1.2.1
  shimmer: ^2.0.0
  geolocator: ^7.0.3
  mdi: ^4.0.0
  table_calendar: ^2.3.3
  measured_size: ^1.0.0
  image_stack: ^2.1.0
  google_fonts: ^2.1.0
  pinput: ^1.2.0
  progress_dialog: ^1.2.4
  image_picker: ^0.8.1+3
  circular_profile_avatar: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  #firebase

  #state management
  provider: ^6.0.0
  #theme and colors
  hexcolor: ^2.0.4

flutter:

  uses-material-design: true
  #assets here
  assets:
    - .env
    - assets/images/
    - assets/fonts/
    - assets/lottie/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DM_Sans/DMSans-Bold.ttf
          weight: 400
        - asset: assets/fonts/DM_Sans/DMSans-Bold.ttf
          weight: 300
        - asset: assets/fonts/DM_Sans/DMSans-Medium.ttf
          weight: 200
        - asset: assets/fonts/DM_Sans/DMSans-Regular.ttf
          weight: 100